name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4  # Updated to v4

      - name: Upload html test report
        uses: actions/upload-artifact@v4  # Updated to v4
        with:
          name: lint.html
          path: D:/AndroidStudioProjects/latest/app/build/reports/lint-results-debug.html
